"""initial_schema

Revision ID: 2572a0e322ab
Revises: 
Create Date: 2026-06-30 20:25:13.662562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2572a0e322ab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs_registry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('apscheduler_id', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('schedule', sa.String(length=100), nullable=True),
    sa.Column('last_run', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_result', sa.String(length=20), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('run_in_mode', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('overnight_safe', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('apscheduler_id')
    )
    op.create_table('machine_state',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('fan_profile', sa.String(length=50), nullable=True),
    sa.Column('rgb_state', sa.String(length=20), nullable=True),
    sa.Column('display_state', sa.String(length=20), nullable=True),
    sa.Column('jobs_paused', sa.Boolean(), nullable=True),
    sa.Column('ups_on_battery', sa.Boolean(), nullable=True),
    sa.Column('ups_battery_pct', sa.Integer(), nullable=True),
    sa.Column('ups_runtime_minutes', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('set_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('set_by', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('machine_state_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('previous_mode', sa.String(length=20), nullable=True),
    sa.Column('new_mode', sa.String(length=20), nullable=True),
    sa.Column('changed_by', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('power_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('ups_battery_pct_at_event', sa.Integer(), nullable=True),
    sa.Column('ups_runtime_minutes_at_event', sa.Integer(), nullable=True),
    sa.Column('action_taken', sa.Text(), nullable=True),
    sa.Column('telegram_notified', sa.Boolean(), nullable=True),
    sa.Column('jobs_paused', sa.Boolean(), nullable=True),
    sa.Column('shutdown_initiated', sa.Boolean(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('apex_id', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('stage', sa.String(length=30), nullable=False),
    sa.Column('owner', sa.String(length=100), nullable=False),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('status_note', sa.Text(), nullable=True),
    sa.Column('live_url', sa.String(length=500), nullable=True),
    sa.Column('internal_url', sa.String(length=500), nullable=True),
    sa.Column('github_repo', sa.String(length=500), nullable=True),
    sa.Column('repo_visibility', sa.String(length=10), nullable=True),
    sa.Column('primary_branch', sa.String(length=50), nullable=True),
    sa.Column('local_path', sa.String(length=500), nullable=True),
    sa.Column('monthly_cost_usd', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('monthly_revenue_usd', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cost_efficiency_flag', sa.String(length=20), nullable=True),
    sa.Column('completeness_score', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('apex_id')
    )
    op.create_table('approval_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('risk_level', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('proposed_action', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('requested_by', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('telegram_message_id', sa.String(length=100), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cost_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('billing_date', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('apex_decision_id', sa.String(length=10), nullable=True),
    sa.Column('date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('options_considered', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('decision_made', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('made_by', sa.String(length=100), nullable=True),
    sa.Column('revisit_trigger', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doc_sync_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('sync_status', sa.String(length=20), nullable=False),
    sa.Column('last_db_write', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_markdown_write', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_check', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_github_commit', sa.DateTime(timezone=True), nullable=True),
    sa.Column('freshness_warning', sa.Boolean(), nullable=True),
    sa.Column('conflict_details', sa.Text(), nullable=True),
    sa.Column('schema_version', sa.String(length=10), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('env_var_requirements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('var_name', sa.String(length=100), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=True),
    sa.Column('stored_in', sa.String(length=200), nullable=True),
    sa.Column('sensitive', sa.Boolean(), nullable=True),
    sa.Column('present', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experiments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('apex_exp_id', sa.String(length=10), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('hypothesis', sa.Text(), nullable=False),
    sa.Column('method', sa.Text(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('conclusion', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('handoffs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('session_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('session_tool', sa.String(length=100), nullable=True),
    sa.Column('what_was_done', sa.Text(), nullable=False),
    sa.Column('what_remains', sa.Text(), nullable=False),
    sa.Column('what_is_blocked', sa.Text(), nullable=False),
    sa.Column('next_model_should', sa.Text(), nullable=False),
    sa.Column('context_pack_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ideas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('raw_description', sa.Text(), nullable=False),
    sa.Column('structured_description', sa.Text(), nullable=True),
    sa.Column('clarification_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('score_total', sa.Integer(), nullable=True),
    sa.Column('score_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('score_explanation', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.String(length=30), nullable=True),
    sa.Column('promoted_to_project_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['promoted_to_project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metric_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('value_text', sa.String(length=200), nullable=True),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_metric_snapshots_project_metric', 'metric_snapshots', ['project_id', 'metric_name', 'snapshot_at'], unique=False)
    op.create_table('model_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('task_type', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('routing_class', sa.String(length=10), nullable=False),
    sa.Column('prompt_package_id', sa.String(length=100), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('data_sensitivity', sa.String(length=10), nullable=True),
    sa.Column('quality_score', sa.Integer(), nullable=True),
    sa.Column('fallback_occurred', sa.Boolean(), nullable=True),
    sa.Column('fallback_reason', sa.String(length=200), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_model_runs_project_provider', 'model_runs', ['project_id', 'provider', 'created_at'], unique=False)
    op.create_table('notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_ext_content_engine',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('publishing_cadence', sa.String(length=100), nullable=True),
    sa.Column('content_pipeline', sa.Text(), nullable=True),
    sa.Column('content_runway', sa.String(length=200), nullable=True),
    sa.Column('seo_status', sa.Text(), nullable=True),
    sa.Column('analytics_status', sa.Text(), nullable=True),
    sa.Column('scheduler_health', sa.String(length=20), nullable=True),
    sa.Column('monetisation_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('promotion_channels', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('image_sources', sa.ARRAY(sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('project_ext_governed_system',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('current_stage', sa.String(length=30), nullable=True),
    sa.Column('stage_gate_status', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('governance_policy', sa.Text(), nullable=True),
    sa.Column('approval_tree', sa.Text(), nullable=True),
    sa.Column('risk_limits', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('champion_strategy', sa.Text(), nullable=True),
    sa.Column('challenger_strategies', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('promotion_criteria', sa.Text(), nullable=True),
    sa.Column('emergency_controls', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('safety_constraints', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('reference_frameworks', sa.ARRAY(sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('project_ext_product_tool',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('maturity_level', sa.String(length=20), nullable=True),
    sa.Column('monetisation_options', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('distribution_channels', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('premium_upgrade_roadmap', sa.Text(), nullable=True),
    sa.Column('marketplace_listings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('project_ext_saas',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('auth_flow', sa.Text(), nullable=True),
    sa.Column('billing_flow', sa.Text(), nullable=True),
    sa.Column('pricing_model', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('free_tier_limits', sa.Text(), nullable=True),
    sa.Column('free_tier_enforcement', sa.String(length=20), nullable=True),
    sa.Column('conversion_funnel', sa.Text(), nullable=True),
    sa.Column('churn_risks', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('growth_levers', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('affiliate_setup', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mrr_usd', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('active_subscribers', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('supporting_signals', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('estimated_effort', sa.String(length=10), nullable=True),
    sa.Column('expected_benefit', sa.Text(), nullable=True),
    sa.Column('suggested_action', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reusable_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source_project_id', sa.UUID(), nullable=True),
    sa.Column('repo_path', sa.String(length=500), nullable=True),
    sa.Column('used_by_projects', sa.ARRAY(sa.UUID()), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('quality_score', sa.Integer(), nullable=True),
    sa.Column('last_validated', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['source_project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('apex_risk_id', sa.String(length=10), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('likelihood', sa.String(length=10), nullable=False),
    sa.Column('impact', sa.String(length=10), nullable=False),
    sa.Column('mitigation', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('tier', sa.String(length=50), nullable=True),
    sa.Column('monthly_cost_usd', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('dashboard_url', sa.String(length=500), nullable=True),
    sa.Column('criticality', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('parent_task_id', sa.UUID(), nullable=True),
    sa.Column('apex_task_id', sa.String(length=10), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('estimated_effort', sa.String(length=20), nullable=True),
    sa.Column('assigned_to', sa.String(length=100), nullable=True),
    sa.Column('blocked_by', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['parent_task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('known_issues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('apex_issue_id', sa.String(length=10), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('discovered_date', sa.Date(), nullable=True),
    sa.Column('workaround', sa.Text(), nullable=True),
    sa.Column('fix_status', sa.String(length=20), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('linked_task_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['linked_task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('known_issues')
    op.drop_table('tasks')
    op.drop_table('services')
    op.drop_table('risks')
    op.drop_table('reusable_assets')
    op.drop_table('recommendations')
    op.drop_table('project_ext_saas')
    op.drop_table('project_ext_product_tool')
    op.drop_table('project_ext_governed_system')
    op.drop_table('project_ext_content_engine')
    op.drop_table('notes')
    op.drop_index('idx_model_runs_project_provider', table_name='model_runs')
    op.drop_table('model_runs')
    op.drop_index('idx_metric_snapshots_project_metric', table_name='metric_snapshots')
    op.drop_table('metric_snapshots')
    op.drop_table('ideas')
    op.drop_table('handoffs')
    op.drop_table('experiments')
    op.drop_table('env_var_requirements')
    op.drop_table('doc_sync_states')
    op.drop_table('decisions')
    op.drop_table('cost_items')
    op.drop_table('approval_requests')
    op.drop_table('projects')
    op.drop_table('power_events')
    op.drop_table('machine_state_history')
    op.drop_table('machine_state')
    op.drop_table('jobs_registry')
    # ### end Alembic commands ###
